BDMarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404 , handler500
import content
from accounts.views import login_request , logout_view
from django_email_verification import urls as mail_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',login_request, name='login'),
    # با استفاده از کد زیر می تونیم از تابع های نوشته شده برای عوض کردن پسورد و بقیه چیزها استفاده کنیم
    path('', include('django.contrib.auth.urls')),
    # لاگ اوت کردن
    path('logout/',logout_view, name='logout'),
    # صفحه اصلی سایت
    path('', include('content.urls'), name='content'),
    path('cart/', include('cart.urls'), name='cart'),
    # بخش اکانت ها که تمامی کارهای مربوط به پروفایل در اینجا رخ می دهد
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('fin/', include('financial.urls'), name='financial'),
    # بخش بلاگ که به شدت کامله :)
    path('blog/', include('blog.urls'), name='blog'),
    #برای ارسال ایمیل فعالسازی اکانت
    path('email/', include(mail_urls)),
    path('api/', include('api_service.urls')),
]

# تو این قسمت ارور ۴۰۴ رو هندل میکنیم و جای ویوش رو میگیم
handler404 = content.views.error_404
handler500 = content.views.error_500
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# این قسمت هم متن های پنل ادمین رو شخصی سازی میکنیم
admin.site.site_header = "پنل ادمین بی دی "
admin.site.site_title = "صفحه شخصی ادمین بی دی"
admin.site.index_title = "خوش اومدید بزرگوار"

blog/urls.py
from django.urls import path
from blog import views
# from .views import AuthorList


app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('page/<int:page>', views.home, name='home'),
    path('category/<slug:slug>', views.category, name='category'),
    path('category/<slug:slug>/page/<int:page>', views.category, name='category'),
    path('article/<slug:slug>', views.detail, name='detail'),
    path('author/<slug:username>', views.show_author_all_articles, name="author"),
	path('author/<slug:username>/<int:page>', views.show_author_all_articles, name="author"),

]

cart/urls.py
from django.urls import path
from cart import views 

app_name = 'cart'

urlpatterns = [
    path('', views.showcart, name='showcart'),
    path('<int:order_pk>/delete', views.delete_order, name='delete_order'),
]

financial/urls.py
from django.urls import path
from financial import views 

app_name = 'financial'

urlpatterns = [
    path('', views.finalize_cart, name='finalize_cart'),
    path('pay/', views.pay, name='pay'),
    path('thanks/', views.success_paid, name='success_paid'),
]

cart/models.py
from django.db import models
from accounts.models import Customer
from Supplier.models import ProductSupplier
from customer.models import CustomerAddress
class Delivery(models.Model):
    """
    table sherkati ke peyk hast
    """    
    company_name = models.CharField(max_length=250)
    phone = models.CharField(max_length=250)

    def __str__(self):
        return self.company_name


class Cart(models.Model):
    """
    sabad khraid
    """    
    Purchase_Status_Choices = [
        ('u', 'Unfinilized'),
        ('f', 'Finalized'),
    ]
    customer_id = models.ForeignKey(Customer, related_name='cart',on_delete=models.CASCADE)
    delivery_id = models.ForeignKey(Delivery, on_delete=models.CASCADE,null=True,blank=True)
    total_price = models.FloatField(default=0)
    status = models.CharField(max_length=1 ,choices=Purchase_Status_Choices, default='u')
    adresses =  models.ForeignKey(CustomerAddress, related_name='cart', null=True,blank=True, on_delete=models.SET_NULL)


class OrderItem(models.Model):
    """
    har itemi ke baraye kharid entekhab mishe va mire to cart
    """    
    cart_id = models.ForeignKey(Cart, related_name='order', on_delete=models.CASCADE)   
    product_supplier_id = models.ForeignKey(ProductSupplier, related_name= 'order',on_delete=models.CASCADE)
    cost = models.FloatField(default=0) #keeps/hold price constant, when car1t status was finalized
    number = models.IntegerField(default=0)

    def __str__(self):
        return str(self.cart_id.id)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.db.models import F
from django.contrib.auth.decorators import login_required

from .models import Cart, OrderItem
from Supplier.models import ProductSupplier
# Create your views here.

from .models import Cart

@login_required
def showcart(request):
    if request.method == 'GET':
        current_customer = request.user.customer
        try:
            current_cart = Cart.objects.get(customer_id=current_customer, status="u")
            # current_cart = get_object_or_404(Cart, customer_id=current_customer, status="u")
            return render(request, 'cart/showcart.html', {'current_cart':current_cart})
        except:
            return render(request, 'cart/showcart.html')
            # 'error': 'Bad info!'


    if request.method == 'POST':
        current_customer = request.user.customer
        prosupid = request.POST.get('prosupid')
        # print(f'\nprosup_id is{prosup_id}')
        prosup = ProductSupplier.objects.get(pk=prosupid)
        current_cart, created = Cart.objects.get_or_create(
                                    customer_id=current_customer,
                                    status='u',)
        # # quantity = int(request.POST.get('quantity'))
        # try:
        #     order_item = OrderItem.objects.get(cart_id=current_cart, product_supplier_id=prosup)
        #     stock = order_item.product_supplier_id.stock
        #     if stock >= order_item.number + quantity:
        #         order_item.number = F('number') + quantity
        #         order_item.save()
        #     else:
        #         msg = 'این تعداد کالا در انبار موجود نمی باشد'
        #         return render(request, 'cart/showcart.html', {'msg':msg})
        #         # return redirect('cart:showcart', {'msg':msg})
        # except OrderItem.DoesNotExist:
        #     obj = OrderItem.objects.create(cart_id=current_cart, product_supplier_id=prosup, number=quantity)
        #     # obj.save()
    
        order_item, created = OrderItem.objects.get_or_create(cart_id=current_cart,
                product_supplier_id=prosup, defaults={'number': 1})
        # if not created:
        #     order_item.number = F('number') + quantity
        #     order_item.save()
        
        return redirect('cart:showcart')

# def finalize_cart(request):
#     if request.method == 'GET':

@login_required
def delete_order(request, order_pk):
    the_cart = request.user.customer.cart.get(status='u')
    order = get_object_or_404(OrderItem, pk=order_pk, cart_id=the_cart)
    if request.method == 'GET':
        order.delete()

        return redirect('cart:showcart')

cart/templates/cart/showcart.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<section class="breadcrumb_part">
  <div class="container">
      <div class="row">
          <div class="col-lg-12">
              <div class="breadcrumb_iner">
                  <h2>سبد خرید</h2>
              </div>
          </div>
      </div>
  </div>
</section>
<div class="container mbottom-40">
  <div class="row">
<div class="col-md-12">
{{ msg }}

  <form
    style="width:100%"
      action="{% url 'financial:finalize_cart' %}"
      method="POST"
    >
    <div class="row">
{% csrf_token %}
    {% for order in current_cart.order.all %}

    <div class="col-md-6">
      <div class="cart-items">
        <ul>

          <li>
            <div class="row">
              <div class="col-md-3">
                <img
                  src="{{ order.product_supplier_id.product_id.product_image.url }}"
                  class="img-responsive"
                >
              </div>
              <div
                class="col-md-9"
                style="position: relative"
              >
                <h5>{{order.product_supplier_id.product_id.product_name}}</h5>
                <p><span>فروشنده : </span>{{order.product_supplier_id.supplier_id.company_name}}</p>
                <p>{{order.product_supplier_id.unit_price}}<span>تومان</span>
                </p>

{% comment %} 
                <form class="form-inline special-form">
                  <button
                    class="btn btn-primary"
                    onclick="cart.trash(4)"
                    id="product-4"
                  >delete</button>
                </form> {% endcomment %}

                <a class="delete-a" href="{% url 'cart:delete_order' order.id %}">حذف</a>

                <label for="{{ order.id }}">تعداد:</label>
                <input type="number" id="{{ order.id }}" name="{{ order.id }}" min="1" max="{{ order.product_supplier_id.stock }}" value="{{ order.number }}">

              </div>
            </div>
          </li>
        </ul>
      </div>


    </div>
    {% empty %}
    <p>سفارشی ثبت نکرده اید!</p>
    {% endfor %}
  </div>
    
      {% comment %} {% csrf_token %} {% endcomment %}
      {% comment %} <input
        type="hidden"
        id="custId"
        name="prosupid"
        value="{{ supplier.id }}"
      > {% endcomment %}

{% if current_cart %}
<hr>
<button class="btn btn-success" style="float:left" type="submit">نهایی شدن خرید</button>
{% endif %}
      
    </form>


  </div>
</div>
</div>



{% endblock %}