BDMarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404 , handler500
import content
from accounts.views import login_request , logout_view
from django_email_verification import urls as mail_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',login_request, name='login'),
    # با استفاده از کد زیر می تونیم از تابع های نوشته شده برای عوض کردن پسورد و بقیه چیزها استفاده کنیم
    path('', include('django.contrib.auth.urls')),
    # لاگ اوت کردن
    path('logout/',logout_view, name='logout'),
    # صفحه اصلی سایت
    path('', include('content.urls'), name='content'),
    path('cart/', include('cart.urls'), name='cart'),
    # بخش اکانت ها که تمامی کارهای مربوط به پروفایل در اینجا رخ می دهد
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('fin/', include('financial.urls'), name='financial'),
    # بخش بلاگ که به شدت کامله :)
    path('blog/', include('blog.urls'), name='blog'),
    #برای ارسال ایمیل فعالسازی اکانت
    path('email/', include(mail_urls)),
    path('api/', include('api_service.urls')),
]

# تو این قسمت ارور ۴۰۴ رو هندل میکنیم و جای ویوش رو میگیم
handler404 = content.views.error_404
handler500 = content.views.error_500
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# این قسمت هم متن های پنل ادمین رو شخصی سازی میکنیم
admin.site.site_header = "پنل ادمین بی دی "
admin.site.site_title = "صفحه شخصی ادمین بی دی"
admin.site.index_title = "خوش اومدید بزرگوار"

blog/urls.py
from django.urls import path
from blog import views
# from .views import AuthorList


app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('page/<int:page>', views.home, name='home'),
    path('category/<slug:slug>', views.category, name='category'),
    path('category/<slug:slug>/page/<int:page>', views.category, name='category'),
    path('article/<slug:slug>', views.detail, name='detail'),
    path('author/<slug:username>', views.show_author_all_articles, name="author"),
	path('author/<slug:username>/<int:page>', views.show_author_all_articles, name="author"),

]

cart/urls.py
from django.urls import path
from cart import views 

app_name = 'cart'

urlpatterns = [
    path('', views.showcart, name='showcart'),
    path('<int:order_pk>/delete', views.delete_order, name='delete_order'),
]

content/urls.py
from django.urls import path, re_path
from content import views
from content.views import SearchProduct


app_name = 'content'

urlpatterns = [
    path('', views.home, name='home'),
    path('categories/', views.categories, name='categories'),
    # path('products/<int:cat_pk>', views.products, name='products'),
    re_path('products/(?P<cat_pk>[0-9]+)$', views.products, name='products'),
    path('productdetails/<int:product_pk>', views.productdetails, name='productdetails'),
    path('search', SearchProduct.as_view(), name='search-product'),
    path('contactus/', views.contactus, name='contactus'),
    path('aboutus/', views.aboutus, name='aboutus'),
]

content/models.py
from django.db import models
from accounts.models import Customer


class SubCategory(models.Model):
    """
        Represent Categories & subCategories & subsub and so on of products like "Home Appliance"
        and "Electrical appliances" and "Refrigerator" with a self-referential foreign key
    """
    cat_name = models.CharField(max_length=50)
    # cat_description = models.TextField(
    #     max_length=1000, blank=True, null=True)
    # cat_image = models.ImageField(
    #     upload_to='content/images/', blank=True, null=True)
    parent_category = models.ForeignKey(
        "self", on_delete=models.SET_NULL, blank=True, null=True, related_name="child_categories")

    def __str__(self):
        return self.cat_name


class Brand(models.Model):
    """
        Represent brands like "LG" with a Foreignkey Relation to subcategory
    """
    brand_name = models.CharField(max_length=250 , verbose_name= "نام برند")
    subcategory_id = models.ForeignKey(
        SubCategory, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.brand_name

class Attribute(models.Model):
    """
        Represent attributes of products
    """
    attr_title = models.CharField(max_length=50, blank=True, null=True , verbose_name= "ویژگی")
    subcategory_id = models.ForeignKey(
        SubCategory, related_name="attr", on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.attr_title

class Product(models.Model):
    """
        Represent every single product like "yakhchal freezer emersan model barfak :D "
    """
    product_name = models.CharField(max_length=250, verbose_name= "نام محصول")
    product_description = models.TextField(
        max_length=1000, blank=True, null=True , verbose_name= "توضیحات محصول")
    product_image = models.ImageField(
        upload_to='content/images/', blank=True, null=True, verbose_name= "تصویر محصول")
    subcategory_id = models.ForeignKey(
        SubCategory, on_delete=models.SET_NULL, blank=True, null=True, verbose_name= "دسته بندی")
    brand_id = models.ForeignKey(
        Brand, on_delete=models.SET_NULL, blank=True, null=True, related_name='brand', verbose_name= "نام برند")
    attribute = models.ManyToManyField(Attribute, through='ProductAttr', verbose_name= "ویژگی")

    def __str__(self):
        return self.product_name




class ProductAttr(models.Model):
    """
        Handle products attributes
    """
    Value_Type_CHOICES = [
        ('INT', 'Integer'),
        ('TXT', 'Text'),
        ('BOOL', 'Bool'),
    ]
    value_type = models.CharField(max_length=4, choices=Value_Type_CHOICES)
    int_value = models.IntegerField(blank=True, null=True)
    text_value = models.TextField(max_length=250, blank=True, null=True)
    bool_value = models.BooleanField(blank=True, null=True)
    product_id = models.ForeignKey(Product, related_name="pro_attr", on_delete=models.CASCADE)
    attr_id = models.ForeignKey(Attribute, related_name="pro_attr", on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.product_id} - {self.attr_id}'


class Feedback(models.Model):
    """
        Represent each user comment and rate to a specific product.
    """
    Rate_CHOICES = [
        (1, '*'),
        (2, '**'),
        (3, '***'),
        (4, '****'),
        (5, '*****'),
    ]
    comment = models.TextField(max_length=250, blank=True, null=True)
    rate = models.IntegerField(choices=Rate_CHOICES, default=5)
    custumer_id = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, blank=True, null=True)
    product_id = models.ForeignKey(
        Product, related_name="feedback", on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f'{self.product_id} - {self.custumer_id}'

content/forms.py
from django import forms

from .models import Feedback

class CommentForm(forms.ModelForm):
    # rate = forms.ChoiceField()

    class Meta:
        model = Feedback
        fields = ('comment', 'rate')

# class SearchForm(forms.Form):
#     search = forms.CharField(required=False,
#                              widget=forms.TextInput(attrs={'size': '40'}))

content/views.py
from django.shortcuts import render,  HttpResponse, redirect
from django.template.defaulttags import register
from django.db.models import Q
from django.views.generic.base import View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import SubCategory, Product, Attribute
from Supplier.models import ProductSupplier
from .forms import CommentForm
# Create your views here.


@register.filter
def get_item(dictionary, key):
    res = str(dictionary.get(key)[0])
    return res

@register.filter
def update_param(myurl, myextra):
    if '?' in myurl:
        res = f'{myurl}&page={myextra}'
    else:
        res = f'{myurl}?page={myextra}'
    return res

def home(request):
    if request.method == 'GET':
        subs = SubCategory.objects.all()

        last_product = Product.objects.all()[:4]

        def list_generator(subs, parent=None):
            lst = []
            try:
                for sub in subs:
                    if sub.parent_category == parent:
                        lst.append(sub)
                        tmp = list_generator(subs, sub)
                        if tmp:
                            lst.append(tmp)
                return lst
            except:
                return HttpResponse('hi')
        lst = list_generator(subs)
        # print(f'list is {lst}')
        return render(request, 'content/home.html', {'subs': lst, 'last_product':last_product})
    else:
        pass



def categories(request):
    if request.method == 'GET':
        return redirect('content:products', cat_pk=3)

def get_parent_cats(cat):
    catlst = []
    f = 1
    catlst.append(cat)
    if cat.parent_category:
        while f:
            catlst.append(cat.parent_category)
            cat = cat.parent_category
            if cat.parent_category == None:
                f = 0
    catlst.reverse()
    return catlst


def get_child_cats(cat):
    catlst = []
    f = 1
    catlst.append(cat)
    if cat.child_categories.all():
        for ccat in cat.child_categories.all():
            get_child_cats(ccat)

    return catlst


def products(request, cat_pk):

    all_cats = SubCategory.objects.all()
    main_cats = all_cats.filter(parent_category=None)

    if request.method == 'GET':
        cat = SubCategory.objects.get(pk=cat_pk)
        catlst = get_child_cats(cat)
        all_products = Product.objects.filter(subcategory_id__in=catlst)
        q = all_products
        # print(request.GET)
        for k, v in request.GET.items():
            if not k == 'page':
                tmpq = Attribute.objects.get(attr_title=k)
                qtype = tmpq.pro_attr.all()[0].value_type
                # print(f'\nqtype is {qtype}')
                if qtype == 'BOOL':
                    q = q.filter(pro_attr__attr_id__attr_title=k,
                                pro_attr__bool_value=v)
                elif qtype == 'INT':
                    q = q.filter(pro_attr__attr_id__attr_title=k,
                                pro_attr__int_value=v)
                elif qtype == 'TXT':
                    q = q.filter(pro_attr__attr_id__attr_title=k,
                                pro_attr__text_value=v)

            # print(f'\nk is {k}')
            # print(f'\nk type is {type(k)}')
            # print(f'\nq is {q}')

        page = request.GET.get('page', 1)

        paginator = Paginator(q, 9)
        try:
            q = paginator.page(page)
        except PageNotAnInteger:
            q = paginator.page(1)
        except EmptyPage:
            q = paginator.page(paginator.num_pages)


        checked_attr = dict(request.GET)
        # print(f'\n checked_attr = {checked_attr}')

        cat = SubCategory.objects.get(pk=cat_pk)
        uniqdict = dict()
        tmp = []
        attrs = cat.attr.all()
        # print(f'\nattrs is {attrs}')
        for attr in attrs:
            for proattr in attr.pro_attr.all():
                if proattr.value_type == 'BOOL':
                    tmp.append(str(proattr.bool_value))
                if proattr.value_type == 'INT':
                    tmp.append(str(proattr.int_value))
                if proattr.value_type == 'TXT':
                    tmp.append(proattr.text_value)
                uniqtmp = list(set(tmp))
            uniqdict[attr] = list(uniqtmp)
            tmp.clear()
            uniqtmp.clear()

        # print(f'\nuniqdict is {uniqdict}')
        catlst = get_parent_cats(cat)
        return render(request, 'content/categories.html',
                      {'all_products': q, 'catlst': catlst, 'cat': cat, 'uniqdict': uniqdict,
                       'checked_attr': checked_attr, 'all_cats': all_cats, 'main_cats': main_cats})


def productdetails(request, product_pk):

    
    this_product = Product.objects.get(pk=product_pk)
    this_product_suppliers = ProductSupplier.objects.filter(
        product_id=this_product, stock__gt=0)
    cat = this_product.subcategory_id
    pro4 = Product.objects.filter(subcategory_id=cat)[:4]
    if request.method == 'GET':

        catlst = get_parent_cats(cat)
        return render(request, 'content/productdetails.html',
                        {'this_product': this_product, 'catlst': catlst,
                        'this_product_suppliers': this_product_suppliers, 'cmform': CommentForm(),
                        'pro4': pro4})
    else:
        try:
            form = CommentForm(request.POST)
            newcm = form.save(commit=False)
            newcm.custumer_id = request.user.customer
            newcm.product_id = Product.objects.get(pk=product_pk)
            newcm.save()
            return redirect('content:productdetails', product_pk)
        except ValueError:
            return render(request, 'content/productdetails.html', 
                {'this_product': this_product, 'catlst': catlst,
                'this_product_suppliers': this_product_suppliers, 'cmform': CommentForm(),
                'pro4': pro4, 'error': 'Bad data passed in!'})


class SearchProduct(View):

    def get(self, request, *args, **kwargs):
        search_text = request.GET['search']
        result = Product.objects.filter(
            Q(product_name__icontains=search_text) |
            Q(product_description__icontains=search_text)
        ).distinct()
        return render(request, 'content/search_result.html', {'search_result': result})


def error_404(request, exception):
    data = {"name": "somthing error"}
    return render(request, 'content/bdmarket404.html', data)


def error_500(request):
    data = {"name": "somthing error"}
    return render(request, 'content/bdmarket404.html', data)

def contactus(request):
    return render(request, 'content/contactus.html')

def aboutus(request):
    return render(request, 'content/aboutus.html')

content/templates/content/productdetails.html
{% extends 'base.html' %}

{% block content %}
{% load static %}



    <section class="breadcrumb_part">
      <div class="container">
          <div class="row">
              <div class="col-lg-3">
                  <div class="breadcrumb_iner">
                      <h2>{{ this_product.product_name }}</h2>
                  </div>
              </div>
              <div class="col-lg-9">
                <ul class="top-list">
                  <li>
                    <a href="{% url 'content:home' %}">بی دی مارکت</a>
                    <span>/</span></li>
                  {% for cat in catlst %}
                  <li><a href="{% url 'content:products' cat.id %}">{{ cat.cat_name }}</a> <span>/</span></li>
                  {% endfor %}
        
                  <li> {{ this_product.product_name }} </li>
        
                </ul>
              </div>
          </div>
      </div>
  </section>
  <div class="bg-color">
    <div class="container-fluid">
    <!-- <div class="row">
      <div class="col-md-12">

        <ul class="top-list">
          <li>
            <a href="{% url 'content:home' %}">بی دی مارکت</a>
            <span>/</span></li>
          {% for cat in catlst %}
          <li><a href="{% url 'content:products' cat.id %}">{{ cat.cat_name }}</a> <span>/</span></li>
          {% endfor %}

          <li> {{ this_product.product_name }} </li>

        </ul>
      </div>
    </div> -->

    <div class="row product-box">

      <div class="col-md-3">
        <img
          src="{{ this_product.product_image.url }}"
          class="img-responsive"
        />

      </div>
      <div class="col-md-9">
        <div class="details">
          <h5>{{ this_product.product_name }}</h5>
          <div class="row">
            <div class="col-5">
              <ul class="dotted">
                <li><span>دسته بندی : </span><a href="{% url 'content:products' this_product.subcategory_id.id %}">{{ this_product.subcategory_id.cat_name }}</a></li>
                <li><span>برند : </span>{{ this_product.brand_id.brand_name }}</li>
              </ul>

              <ul class="text-list">
                {% for proattr in this_product.pro_attr.all %}
                <li> {{ proattr.attr_id.attr_title }}:
                  {% if proattr.value_type == 'BOOL' %}
                  {% if proattr.bool_value %}
                  دارد
                  {% else %}
                  ندارد
                  {% endif %}
                  {% elif proattr.value_type == 'INT' %}
                  {{ proattr.int_value }} عدد
                  {% elif proattr.value_type == 'TXT' %}
                  {{ proattr.text_value }}
                  {% endif %}

                </li>
                {% endfor %}
              </ul>
              <p>توضیحات: {{ this_product.product_description }} </p>
              <div class="row">
                <div class="col-md-12">
                  <hr>
                </div>
              </div>
              <div class="row icon-section">
                <div class="col-md-3 pleft-0">

                  <div class="row">

                    <div class="col-md-4 pleft-0 pright-0">
                      <img
                        src="{% static 'img/icon-1.png' %}"
                    
                      /></div>
                    <div class="col-md-8"> ضمانت اصل بودن کالا</div>
                  </div>


                </div>
                <div class="col-md-3 pleft-0">
                  <div class="row">
                    <div class="col-md-4 pleft-0 pright-0">
                      <img
                      src="{% static 'img/icon-2.png' %}"
                        
                      >
                    </div>
                    <div class="col-md-8">
                      7 روز هفته 24 ساعته
                    </div>
                  </div>
                </div>
                <div class="col-md-3 pleft-0">
                  <div class="row">
                    <div class="col-md-4 pleft-0 pright-0">
                      <img
                      src="{% static 'img/icon-3.png' %}"
                     
                      >
                    </div>
                    <div class="col-md-8">
                      امکان تحویل اکسپرس
                    </div>
                  </div>
                </div>
                <div class="col-md-3 pleft-0">
                  <div class="row">
                    <div class="col-md-4 pleft-0 pright-0">
                      <img
                      src="{% static 'img/icon-4.png' %}"
                      
                      >
                    </div>
                    <div class="col-md-8">
                      امکان پرداخت در محل
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-7">
              <div class="side-details-box">
                <table class="table table-seller">
                  {% for supplier in this_product_suppliers %}
                  <tr>
                    <td>
                      {{ supplier.supplier_id.company_name }}
                    </td>
                    <td>{{ supplier.unit_price }} تومان</td>
                    <td>

                      <form style="width:100% !important"
                        class=""
                        action="{% url 'cart:showcart' %}"
                        method="POST"
                      >
                        {% csrf_token %}
                        <input
                          type="hidden"
                          id="custId"
                          name="prosupid"
                          value="{{ supplier.id }}"
                        >
                        {% comment %} <label for="quantity">تعداد:</label>
                        <input
                          type="number"
                          id="quantity"
                          name="quantity"
                          min="1"
                          max="{{ supplier.stock|add:'0' }}"
                          value="1"
                        > {% endcomment %}
                        <button type="submit"> افزودن به سبد</button>
                      </form>

                    </td>

                  </tr>
                  {% endfor %}
                </table>
              </div>

            </div>
          </div>

        </div>
      </div>


    </div>
    <div class="row">
      <div class="col-md-12">
        {% comment %} <h5 class="title-table">لیست فروشنده / گارانتی های این محصول
          <a href="#">کالای خود را در دیجی کالا بفروشید</a>
        </h5> {% endcomment %}


      </div>
    </div>
    <div class="row mbottom-30 mtop-30">
   
      <div class="col-md-12">
        <div class="w3-bar w3-black">
     <h4><i class="fa fa-pen"></i>
               محصولات مرتبط
           </h4>
     
           </div>
     </div>
          
     {% for pro in pro4 %}
      <div class="col-md-3">

        <a
          class="relate-product"
          href="{% url 'content:productdetails' pro.id %}"
          target="_blank"
        >
          <img
            src="{{ pro.product_image.url }}"
            class="img-responsive"
          />
          <h6>
            {{ pro.product_name }}
            {% comment %} <p>1,200,000 تومان</p> {% endcomment %}
          </h6>
        </a>
      </div>
      {% endfor %}
   
    </div>
    <!--            <div class="owl-carousel owl-theme" >-->
    <!--                <div class="item"><img src="img-3.jpg"></div>-->
    <!--                <div class="item"><h4>2</h4></div>-->
    <!--                <div class="item"><h4>3</h4></div>-->
    <!--                <div class="item"><h4>4</h4></div>-->
    <!--                <div class="item"><h4>5</h4></div>-->
    <!--                <div class="item"><h4>6</h4></div>-->
    <!--                <div class="item"><h4>7</h4></div>-->
    <!--                <div class="item"><h4>8</h4></div>-->
    <!--                <div class="item"><h4>9</h4></div>-->
    <!--                <div class="item"><h4>10</h4></div>-->
    <!--                <div class="item"><h4>11</h4></div>-->
    <!--                <div class="item"><h4>12</h4></div>-->
    <!--            </div>-->
  </div>
  <div class="container-fluid">
    <div class="row mright-0 mleft-0">
<div class="col-md-12">
   <div class="w3-bar w3-black">
<h4><i class="fa fa-comment"></i>نظرات
          کاربران
      </h4>

      </div>
</div>
     


      <div
        id="comment"
        class="w3-container tab tab-comment"
      >

      
        <form
          class="alaki"
          action="{% url 'content:productdetails' this_product.id %}"
          method="POST"
        >
          {% csrf_token %}
          {{cmform}}
          <button type="submit"> ثبت نظر</button>
        </form>



        {% comment %} {{error}} {% endcomment %}
        {% for feedback in this_product.feedback.all %}
        <div class="row">
          <div class="col-md-4">
            <ul class="">
              <li>
                <h6>{{ feedback.custumer_id.user.get_full_name }}</h6>
              </li>
              {% comment %} <li class="date">در تاریخ 11 دی 1398</li> {% endcomment %}


            </ul>
          </div>
          <div class="col-md-8">


            <p>{{ feedback.comment }}</p>
            <hr>
            {{ feedback.get_rate_display }}
          </div>
        </div>
        {% endfor %}
      </div>



      <div
        class="row"
        style="text-align: center !important;"
      >

      
      </div>

    </div>
  </div>


  {% endblock %}

content/templates/content/products.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

{% comment %} <h1>
  {{ cat.cat_name }}
</h1> {% endcomment %}
<div class="container-fluid">


  <div
    class="row"
    style="background-color: #f5f5f5;"
  >
    <div class="col-md-12">
      <ul class="top-list">
        <li>
          <a href="{% url 'content:home' %}">بی دی مارکت</a>
          <span>/</span></li>
        {% for cat in catlst %}
        {% if not forloop.last %}
        <li><a href="{% url 'content:products' cat.id %}">{{ cat.cat_name }}</a> <span>/</span></li>
        {% else %}
        <li>{{ cat.cat_name }}</li>
        {% endif %}
        {% endfor %}

      </ul>
    </div>
  </div>


  <div class="row">

    <div class="col-md-2" style="direction: rtl;">

       <form class="form-filter"
        action="{% url 'content:products' cat.id %}" 
        method="GET"
      >
      <!-- ?get_parameter_name='{{ tag_name }}' -->
      {% comment %} {{ checked_attr.'ساید بای ساید' }} {% endcomment %}
    
        {% for attr, vlst in uniqdict.items %}
        <br>{{ attr.attr_title }}

        
       
          <ul class="pright-0">
            {% for v in vlst %}
            
       
        
        

            {% if attr.attr_title in checked_attr.keys and v == checked_attr|get_item:attr.attr_title %}

            <li class="form-group">
              
                {% if attr.pro_attr.all.first.value_type == "BOOL" %}
                {% if v == 'True' %}
                  <input type="checkbox" id="{{ attr.attr_title }}" name="{{ attr }}" value="True" checked>
                  <label for="{{ attr.attr_title }}">دارد</label>
                {% else %}
                  <input type="checkbox" id="{{ attr.attr_title }}" name="{{ attr }}" value="False" checked>
                  <label for="{{ attr.attr_title }}">ندارد</label>
                {% endif %}
                {% elif attr.pro_attr.all.first.value_type == 'INT' %}
                  <input type="checkbox" id="{{ attr.attr_title }}" name="{{ attr }}" value="{{ v }}" checked>
                  <label for="{{ attr.attr_title }}">{{ v }} عدد</label>
                {% elif attr.pro_attr.all.first.value_type == 'TXT' %}
                  <input type="checkbox" id="{{ attr.attr_title }}" name="{{ attr }}" value="{{ v }}" checked>
                  <label for="{{ attr.attr_title }}">{{ v }}</label>
                {% endif %}
              
            </li>
            
            {% else %}
            
            <li class="form-group">
              
                {% if attr.pro_attr.all.first.value_type == "BOOL" %}
                {% if v == 'True' %}
                  <input type="checkbox" id="{{ attr.attr_title }}" name="{{ attr }}" value="True">
                  <label for="{{ attr.attr_title }}">دارد</label>
                {% else %}
                  <input type="checkbox" id="{{ attr.attr_title }}" name="{{ attr }}" value="False">
                  <label for="{{ attr.attr_title }}">ندارد</label>
                {% endif %}
                {% elif attr.pro_attr.all.first.value_type == 'INT' %}
                  <input type="checkbox" id="{{ attr.attr_title }}" name="{{ attr }}" value="{{ v }}">
                  <label for="{{ attr.attr_title }}">{{ v }} عدد</label>
                {% elif attr.pro_attr.all.first.value_type == 'TXT' %}
                  <input type="checkbox" id="{{ attr.attr_title }}" name="{{ attr }}" value="{{ v }}">
                  <label for="{{ attr.attr_title }}">{{ v }}</label>
                {% endif %}
              
            </li>

           {% endif %}
            {% endfor %}
          </ul>
        
        {% endfor %}
        <input type="submit" value="Submit" class="btn btn-primary">
      </form> 

    </div>
    <div class="col-md-10">

      <div class="row">
        {% for product in all_products %}
        <div class="col-md-3 mbottom-30">
          <a
            href="{% url 'content:productdetails' product.id %}"
            target="_blank"
            class="pcard"
          >
          {% if product.product_image %}
            <img
              src="{{ product.product_image.url }}"
              class="img-responsive"
            >
            {% endif %}
            <ul class="color-div">
            </ul>
            <h6>{{ product.product_name }}</h6>
            <ul>
              {% comment %} <li>2876000 <span class="toman">تومان</span></li> {% endcomment %}
              {% comment %} <button>افزودن به سبد خرید</button> {% endcomment %}
            </ul>

          </a>
        </div>
        {% endfor %}
      </div>

    </div>
  </div>



</div>


{% comment %} <div class="card-columns">
  {% for product in all_products %}
  <div class="card">
    <img
      class="card-img-top"
      src="/media/{{ product_image }}"
      alt="Card image cap"
    >
    <div class="card-body">
      <h5 class="card-title">Card title that wraps to a new line</h5>
      <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    </div>
  </div>
  {% endfor %} {% endcomment %}
</div>

{% if all_products.has_other_pages %}
  <ul class="pagination">
    {% if all_products.has_previous %}
      <li><a href="{{ request.get_full_path|update_param:all_products.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in all_products.paginator.page_range %}
      {% if all_products.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="{{ request.get_full_path|update_param:i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if all_products.has_next %}
      <li><a href="{{ request.get_full_path|update_param:all_products.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}

content/templates/content/search_result.html
{% extends 'base.html' %}


{% block content %}
{% if search_result %}




{% comment %} <h1>
  {{ cat.cat_name }}
</h1> {% endcomment %}
<div class="container-fluid">


  <div
    class="row"
    style="background-color: #f5f5f5;"
  >
    <div class="col-md-12">
      <ul class="top-list">
        <li>
          <a href="{% url 'content:home' %}">بی دی مارکت</a>
          <span>/</span></li>
        <li>نتیجه جستجو</li>

      </ul>
    </div>
  </div>


  <div class="row">

    <div class="col-md-2" style="direction: rtl;">

      
    </div>
    <div class="col-md-10">

      <div class="row">
        {% for product in search_result %}
        <div class="col-md-3 mbottom-30">
          <a
            href="{% url 'content:productdetails' product.id %}"
            target="_blank"
            class="pcard"
          >
          {% if product.product_image %}
            <img
              src="{{ product.product_image.url }}"
              class="img-responsive"
            >
            {% endif %}
            <ul class="color-div">
            </ul>
            <h6>{{ product.product_name }}</h6>
            <ul>
             
            </ul>

          </a>
        </div>
        {% endfor %}
      </div>

    </div>
  </div>







{% else %}
<p>Not Found!</p>

{% endif %}




{% endblock content %}