BDMarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404 , handler500
import content
from accounts.views import login_request , logout_view
from django_email_verification import urls as mail_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',login_request, name='login'),
    # با استفاده از کد زیر می تونیم از تابع های نوشته شده برای عوض کردن پسورد و بقیه چیزها استفاده کنیم
    path('', include('django.contrib.auth.urls')),
    # لاگ اوت کردن
    path('logout/',logout_view, name='logout'),
    # صفحه اصلی سایت
    path('', include('content.urls'), name='content'),
    path('cart/', include('cart.urls'), name='cart'),
    # بخش اکانت ها که تمامی کارهای مربوط به پروفایل در اینجا رخ می دهد
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('fin/', include('financial.urls'), name='financial'),
    # بخش بلاگ که به شدت کامله :)
    path('blog/', include('blog.urls'), name='blog'),
    #برای ارسال ایمیل فعالسازی اکانت
    path('email/', include(mail_urls)),
    path('api/', include('api_service.urls')),
]

# تو این قسمت ارور ۴۰۴ رو هندل میکنیم و جای ویوش رو میگیم
handler404 = content.views.error_404
handler500 = content.views.error_500
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# این قسمت هم متن های پنل ادمین رو شخصی سازی میکنیم
admin.site.site_header = "پنل ادمین بی دی "
admin.site.site_title = "صفحه شخصی ادمین بی دی"
admin.site.index_title = "خوش اومدید بزرگوار"

accounts/urls.py
from django.urls import path
from . import  views



app_name = 'accounts'

urlpatterns=[

# هر ویو به ترتیب حضور در اینجا در قسمت ویوها هست


# قسمت ثبت نام


    # در اینجا صفحه ای هست که کاربر انتخاب میکنه فروشنده باشه یا خریدار
    path('register/',views.register, name='register'),
    # کاربر به صفحه ثبت نام به عنوان فروشنده هدایت میشه
    path('supplier_register/',views.SupplierRegister.as_view(), name='supplier_register'),
    # کاربر به صفحه ثبت نام به عنوان خریدار منتقل میشه
    path('customer_register/',views.CustomerRegister.as_view(), name='customer_register'),
    # پس از ثبت نام به این صفحه منتقل میشه که میگه ایمیلی براش ارسال شده
    path('registersen-mail/',views.registersendmail, name='registersendmail'),
    # پس از تکمیل ثبت نام و کلیک رو دکمه داشبورد به اینجا فرستاده میشود که پر است از فانکشنالیتی
    path('profile/', views.Profile.as_view(), name="profile"),
    

 
#قسمت مقالات 
 
    #اینجا هر کاربر لیست مقالات خودش را میبیند ولی سوپر یوزر می تواند همه مقالات موجود در سایت رو در اینجا ببیند و با توجه به دکه هایی که تعبیه شده امکان ححذف یا ویرایش انها را دارد
    path('', views.ArticleList.as_view(), name='home'),
    # در اینجا هر کاربر می تواند مقاله ارسال کند ولی وضعیت این مقاله همیشه پیشنویس است و تا تایید ادمین در سایت نمایش داده نمیشود
    path('article/create/', views.ArticleCreate.as_view(), name="article-create"),
    # در اینجا می توان مقاله را اصلاح تمود
    path('article/update/<int:pk>', views.ArticleUpdate.as_view(), name="article-update"),
    # در اینجا هم مقاله حذف میشود
    path('article/delete/<int:pk>', views.ArticleDelete.as_view(), name="article-delete"),
    

# قسمت خریدار

    # در این قسمت خریدار ادرس جدیدی اضافه میکند 
    path('addrescostomeradd/', views.addrescostomeradd.as_view(), name="addrescostomeradd"),
    # در اینجا خریدار تمام ادرس های خودش رو می تونه ببینه
    path('addrescostomershow/', views.addrescostomershow.as_view(), name="addrescostomershow"),
    # در اینجا ادرس حذف میشود
    path('adrrsssdelete/<int:pk>', views.adrrsssdelete.as_view(), name="adrrsssdelete"),
    # در اینجا ادرس اصلاح میشود
    path('addrescostomerupdate/<int:pk>', views.addrescostomerupdate.as_view(), name="addrescostomerupdate"),
    # در اینجا مشتری تاریخچه خرید خودش را میبیند
    path('buyhistory/', views.buyhistory, name='buyhistory'),



# قسمت فروشنده
    
    # در این قسمت فروشنده تمامی اجناس موجود در سایتش را میبیند
    path('stock/', views.StockList.as_view(), name='stock-list'),
    # در اینجا می تواند تعداد اجناس را کم یا زیاد نماید
    path('editMojodi/<int:pk>', views.editMojodiestock.as_view(), name='editMojodiestock'),
    # در اینجا می تواند ان محصول را حذف کند
    path('deletestock/<int:pk>', views.stockdelete.as_view(), name='delete-stock'),
    # در اینجا می تواند قیمت محصول را عوض کند
    path('editpricestock/<int:pk>', views.editpricestock.as_view(), name='editpricestock'),
    # در اینجا می تواند محصولی را اضافه نماید
    path('addstock/', views.stoockCreate.as_view(), name='add-stock'),
    # پس از اضافه کردن محصول در اینجا محصول را تایید نهایی می کند و مقادیر قیمت و تعداد که منحصر به فرد اوست را تغییر میدهد
    # در ضمن فروشنده مستقیما اجناسی که در فروشگاه هستند را از این مسیر اعلام امادگی فروش کند ودیگر نیازی به تعریف جنس نیست
    path('confirmstock/', views.ConfrimCreate.as_view(), name='confirm-stock'),
    # در اینجا برای محصول ویژگی تعیین میکند
    path('addattribute/', views.AddAttribute.as_view(), name='addattr'),
    # در اینجا یک برند تعیین میکند
    path('addbrand/', views.addbrand.as_view(), name='addbrand'),
    # 
    # path('productattr/', views.ProductAttr.as_view(), name='ProductAttr'),
]

blog/urls.py
from django.urls import path
from blog import views
# from .views import AuthorList


app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('page/<int:page>', views.home, name='home'),
    path('category/<slug:slug>', views.category, name='category'),
    path('category/<slug:slug>/page/<int:page>', views.category, name='category'),
    path('article/<slug:slug>', views.detail, name='detail'),
    path('author/<slug:username>', views.show_author_all_articles, name="author"),
	path('author/<slug:username>/<int:page>', views.show_author_all_articles, name="author"),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

class User(AbstractUser):
    is_customer = models.BooleanField(default=False)
    is_supplier = models.BooleanField(default=False)
    first_name = models.CharField(max_length=100, verbose_name="نام")
    last_name = models.CharField(max_length=100 , verbose_name="نام خانوادگی")
    email = models.EmailField(unique=True, verbose_name='ایمیل')
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    EMAIL_FIELD = 'email'
    
    

gender_choices = [
         ('M', 'Male'), 
         ('F', 'Female')
      ]
city_choices = [
        ('tehran', 'Tehran'),
        ('ardebil', 'Ardebil'),
        ('rasht', 'Rasht'),
        ('kerman', 'Kerman'),
        ('ahvaz', 'Ahvaz')
    ]  

    
class Customer(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='customer', on_delete = models.CASCADE, primary_key = True)
    phone_number = models.CharField(max_length=20, verbose_name= "شماره تلفن همراه")
    gender = models.CharField(max_length=50, choices=gender_choices, verbose_name='جنسیت')
    city = models.CharField(max_length=50, choices=city_choices , verbose_name= "شهر")


class Supplier(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='supplier', on_delete = models.CASCADE, primary_key = True)
    phone_number = models.CharField(max_length=20,verbose_name= "شماره تلفن همراه")
    company_name = models.CharField(max_length=50,verbose_name= "نام شرکت")
    address = models.TextField(max_length=500)
    city = models.CharField(max_length=50, choices=city_choices)

    def __str__(self):
        return self.company_name

accounts/views.py
from django.contrib.auth import login, logout,authenticate
from django.shortcuts import redirect, render
from django.contrib import messages
from django.views.generic import CreateView , ListView , UpdateView , DeleteView
from .form import CustomerSignUpForm, SupplierSignUpForm , ProfileForm , ConfrimForm
from django.contrib.auth.forms import AuthenticationForm
from .models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from blog.models import Article
from Supplier.models import ProductSupplier
from accounts.mixin import FieldsMixin , FormValidMixin , SuperUserAccessMixin , AuthorsAccessMixin  , FormStockValidMixin 
from content.models import Product , Attribute , Brand , ProductAttr 
from django.urls import reverse_lazy
from accounts.models import User
from django.contrib.auth.views import PasswordChangeView 
from customer.models import CustomerAddress
from cart.models import Cart
from django_email_verification import sendConfirm

# توضیحات در قسمت یو ار ال امده است
# قسمت ثبت نام
# در اینجا صفحه ای هست که کاربر انتخاب میکنه فروشنده باشه یا خریدار
def register(request):
    return render(request, 'accounts/register.html')

class SupplierRegister(CreateView):
    model = User
    form_class = SupplierSignUpForm
    template_name = 'accounts/supplier_register.html'

    def form_valid(self, form):
        user = form.save()
        sendConfirm(user)
        # login(self.request, user)
        return redirect('accounts:registersendmail')

class CustomerRegister(CreateView):
    model = User
    form_class = CustomerSignUpForm
    template_name = 'accounts/customer_register.html'

    def form_valid(self, form):
        user = form.save()
        sendConfirm(user)
        # login(self.request, user)
        return redirect('accounts:registersendmail')

def registersendmail(request):
    return render(request, 'accounts/afterrejister.html')



class Profile(UpdateView):
    model = User
    template_name = "registration/profile.html"
    form_class = ProfileForm
    
    success_url = reverse_lazy("accounts:profile")
    def get_object(self):
        return User.objects.get(pk = self.request.user.pk)
    def get_form_kwargs(self):
        kwargs = super(Profile, self).get_form_kwargs()
        kwargs.update({
			'user': self.request.user
		})
        return kwargs





#قسمت مقالات 
class ArticleList(LoginRequiredMixin , ListView):
    template_name = "registration/home.html"
    def get_queryset(self):
        if self.request.user.is_superuser:
            return Article.objects.all()
        else:
            return Article.objects.filter(author=self.request.user)


class ArticleCreate(LoginRequiredMixin, FormValidMixin, FieldsMixin, CreateView):
	model = Article
	template_name = "registration/article-create-update.html"



class ArticleUpdate(LoginRequiredMixin, FormValidMixin, FieldsMixin, UpdateView):
	model = Article
	template_name = "registration/article-create-update.html"

class ArticleDelete(SuperUserAccessMixin , DeleteView):
	model = Article
	success_url = reverse_lazy('accounts:home')
	template_name = "registration/article_confirm_delete.html"







# قسمت خریدار

class addrescostomeradd(LoginRequiredMixin, CreateView):
    model = CustomerAddress
    fields = ['address', 'city', 'postalcode']
    template_name = "registration/addadress.html" 
    success_url = reverse_lazy('accounts:addrescostomershow')

    def get_context_data(self, **kwargs):
        context=super(addrescostomeradd, self).get_context_data(**kwargs)
        context[next]=self.request.GET['next']
        return context

    def form_valid(self, form):
        d = form.save(commit=False)
        d.customer_id = self.request.user.customer
        d.save()
        return super().form_valid(form)


    def get_success_url(self):
        redirect_to=self.request.GET['next']
        return redirect_to



class addrescostomershow(LoginRequiredMixin , ListView):
    template_name = "registration/Alladress.html"
    def get_queryset(self):
        return CustomerAddress.objects.filter(customer_id=self.request.user.customer)



class addrescostomerupdate(LoginRequiredMixin, UpdateView):
    model = CustomerAddress
    fields = ['address', 'city', 'postalcode']
    template_name = "registration/addadress.html"
    success_url = reverse_lazy('accounts:addrescostomershow')

class adrrsssdelete(LoginRequiredMixin, DeleteView):
    model = CustomerAddress
    success_url = reverse_lazy('accounts:addrescostomershow')
    template_name = "registration/addresstock.html"



def buyhistory(request):

    if request.method=='GET':
        current_customer = request.user.customer
        carts = Cart.objects.filter(customer_id=current_customer, status="f")

        return render(request, 'accounts/buyhistory.html', {'carts':carts})







# قسمت فروشنده

class StockList(LoginRequiredMixin , ListView):
    template_name = "registration/AllStock.html"
    def get_queryset(self):
        return ProductSupplier.objects.filter(supplier_id=self.request.user.supplier)

class editpricestock(LoginRequiredMixin,UpdateView):
    model = ProductSupplier
    fields = ['unit_price']
    success_url = reverse_lazy('accounts:stock-list')
    template_name = "registration/editpricestock.html"

class stockdelete(LoginRequiredMixin, DeleteView):
    model = ProductSupplier
    success_url = reverse_lazy('accounts:stock-list')
    template_name = "registration/deletstock.html"


class stoockCreate(LoginRequiredMixin, CreateView):
    model = Product
    fields = [
			"product_name", "product_description", "product_image",
			"subcategory_id", "brand_id", "attribute"
		]
    success_url = reverse_lazy('accounts:confirm-stock')
    template_name = "registration/addstock.html"
    
class AddAttribute(LoginRequiredMixin, CreateView):
    model = Attribute
    fields = ["attr_title"]
    success_url = reverse_lazy('accounts:add-stock')
    template_name = "registration/AddAttribute.html"

# class ProductAttr(LoginRequiredMixin, CreateView):
#     model = ProductAttr
#     fields = ["value_type","int_value","text_value","bool_value","product_id",'attr_id']
#     success_url = reverse_lazy('accounts:add-stock')
#     template_name = "registration/ProductAttr.html"
    


class addbrand(LoginRequiredMixin, CreateView):
    model = Brand
    fields = ["brand_name"] 
    success_url = reverse_lazy('accounts:add-stock')
    template_name = "registration/addbrand.html"



class ConfrimCreate(LoginRequiredMixin, CreateView):
    model = ProductSupplier
    fields = ['product_id', 'unit_price', 'stock']
    template_name = "registration/confrmstock.html" 
    success_url = reverse_lazy('accounts:stock-list')
    def form_valid(self, form):
        if not self.request.user.is_superuser:
            d = form.save(commit=False)
            d.supplier_id = self.request.user.supplier
            d.save()
            return super().form_valid(form)
        
class editMojodiestock(LoginRequiredMixin,UpdateView):
    model = ProductSupplier
    fields = ['stock']
    success_url = reverse_lazy('accounts:stock-list')
    template_name = "registration/editojodistock.html"










# در اینجا دو صفحه شخصی شده تغییر پسورود و تایید ان را نمایش میدهد
class PasswordChange(PasswordChangeView):
    success_url = reverse_lazy('accounts:password_change_done')

def PasswordChangeDoneView(request):
    return render(request, 'accounts/v.html')








# دو تابع زیر کار ورود و خروج را انجام می دهند 
def login_request(request):
    if request.method=='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None :
                login(request,user)
                return redirect('accounts:profile')
            else:
                messages.error(request,"Invalid username or password")
        else:
                messages.error(request,"Invalid username or password")
    return render(request, 'registration/login.html',
    context={'form':AuthenticationForm()})

def logout_view(request):
    logout(request)
    return redirect('/')

accounts/templates/accounts/afterrejister.html
<h1> لینک عضویت ارسال شد لطفا ایمیل خود را چک نمایید</h1>

accounts/templates/accounts/buyhistory.html
{% extends 'registration/admin.html' %}

{% block title %}{% block title-meta %}
تاریخچه خرید
{% endblock %}{% endblock %}
{% block main %}


{% for cart in carts %}

<div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0">
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th>id</th>
                      
                      <th>نام کالا</th>
                      <th>فروشنده</th>
                      <th>قیمت</th>
                      <th>تعداد</th>

                      {% comment %} <th>تعداد</th> {% endcomment %}
                      
                      
                    
                    </tr>
                  </thead>
                  <tbody>
                    {% for order in cart.order.all %}

                    <tr>
                      
                      <td>{{ order.id }}</td>
                      <td>{{ order.product_supplier_id.product_id.product_name }}</td>
                      <td>{{ order.product_supplier_id.supplier_id.company_name }}</td>
                      <td>{{ order.cost }}</td>
                      <td>{{ order.number }}</td>

                      

                    </tr>
                    
                    {% endfor %}
                    
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>


{% endfor %}


{% endblock %}

accounts/templates/accounts/customer_register.html
{% load widget_tweaks %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'registration/login/css/rtl.css' %}">
    <title>ثبت نام</title>
</head>
<body>

    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>ثبت نام </h2>
                </div>
                <div class="card-body">
                    <form action="{% url 'accounts:customer_register' %}" method="POST" novalidate>
                      {% csrf_token %}
                         {% for field in form.visible_fields %}
                           <div class="form-group">
                               {{ field.label_tag }}
                                  {% render_field field class="form-control" %}
                                    {% for error in field.errors %}
                                      <span style="color:red">{{ error }}</span>
                                    {% endfor %}
                         {% endfor %}
                             <input type="submit" value="ثبت نام" class="btn btn-block btn-primary">
                           </div>
                    </form>
                 </div>
                    </div>   
                </div>
              </div>
            </div>
        </div>
      </section>

</body>
</html>

accounts/templates/accounts/login.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    <title>Demo Registration</title>
</head>
<body>

    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>Login</h2>
                </div>
                <div class="card-body">
                    <form action="{% url 'accounts:login' %}" method="POST" novalidate>
                      {% csrf_token %}
                         {% for field in form.visible_fields %}
                           <div class="form-group">
                               {{ field.label_tag }}
                                  {% render_field field class="form-control" %}
                                    {% if messages%}
                                      {% for message in messages %}
                                        <span style="color:red">{{ message }}</span>
                                      {% endfor %}
                                     {% endif %}
                         {% endfor %}
                         <br>
                             <input type="submit" value="Login" class="btn btn-block btn-primary">
                           </div>
                    </form>
                 </div>
                    </div>   
                </div>
              </div>
            </div>
        </div>
      </section>

</body>
</html>

accounts/templates/accounts/password_change_done.html
{% extends 'registration/admin.html' %}
{% block title %}{% block title-meta %}
	گذرواژه با موفقیت تغییر یافت
{% endblock %}{% endblock %}

{% block main %}
<div class="col-md-8 text-center mx-auto">
  <div class="card card-success">
    <div class="card-header">
      <h3 class="card-title mb-0 float-left">پیام</h3>
    </div>
		<div class="card-body py-4">
			<p>گذرواژه با موفقیت تغییر یافت</p>
		</div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'registration/login/css/rtl.css' %}">
    <title style="text-align: center;">ثبت نام</title>
</head>
<body>

    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>ثبت نام</h2>
                </div>
                <div class="card-body">
                    <div class="row">
                       <div class="col-lg-6">
                        <a type="button" class="btn btn-block" href="{% url 'accounts:customer_register' %}">ثبت نام به عنوان خریدار</a>
                       </div>
                       <div class="col-lg-6">
                        <a type="button" class="btn btn-block" href="{% url 'accounts:supplier_register' %}">ثبت نام به عنوان فروشنده</a>
                       </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
  


</body>
</html>

accounts/templates/accounts/supplier_register.html
{% load widget_tweaks %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'registration/login/css/rtl.css' %}">
    <title>ثبت نام</title>
</head>
<body style="direction: rtl;">

    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>ثبت نام</h2>
                </div>
                <div class="card-body">
                    <form action="{% url 'accounts:supplier_register' %}" method="POST" novalidate>
                      {% csrf_token %}
                         {% for field in form.visible_fields %}
                           <div class="form-group">
                               {{ field.label_tag }}
                                  {% render_field field class="form-control" %}
                                    {% for error in field.errors %}
                                      <span style="color:red">{{ error }}</span>
                                    {% endfor %}
                         {% endfor %}
                             <input type="submit" value="ثبت نام" class="btn btn-block btn-primary">
                           </div>
                    </form>
                 </div>
                    </div>   
                </div>
              </div>
            </div>
        </div>
      </section>

</body>
</html>